src/Entity/Page.php
<?php

namespace App\Entity;

use App\Components\Language\CurrentLanguage;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Page
 * @package PageBundle\Entity
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @ORM\Table(name="page")
 * @ORM\HasLifecycleCallbacks()
 */
class Page {

  /**
   * @ORM\Column(type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;
  /**
   * ORIGINAL LANGUAGE
   * @ORM\Column(type="string", length=191)
   */
  private $language;

  /**
   * @ORM\OneToMany(targetEntity="PageData", mappedBy="page", cascade={"persist", "remove"})
   */
  private $data;

  /**
   * @ORM\ManyToOne(targetEntity="User")
   * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
   */
  private $user;

  /**
   * @ORM\OneToMany(targetEntity="Comment", mappedBy="page", cascade={"persist", "remove"})
   */
  private $comments;

  public function __construct()
  {
    $this->data = new ArrayCollection();
    $this->comments = new ArrayCollection();
  }

  /**
   * Get id
   *
   * @return integer
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @return mixed
   */
  public function getUser()
  {
    return $this->user;
  }


  public function setUser(User $user)
  {
    $this->user = $user;
  }

  /**
   * @return mixed
   */
  public function getLanguage()
  {
    return $this->language;
  }

  /**
   * @param mixed $language
   */
  public function setLanguage($language): void
  {
    $this->language = $language;
  }

  public function addData( PageData $data ){
    $data->setPage($this);
    $this->data->add($data);
  }

  public function removeData( PageData $data ){
    $this->data->remove($data);
  }

  public function getData(){
    return $this->data;
  }
  public function getEntities(){
    $entities = [];
    foreach ($this->data->toArray() as $data){
      $entities[$data->getLanguage()] = $data;
    }
    return $entities;
  }

  /**
   * @param null $language
   * @return PageData
   */
  public function getEntity( $language = null ){
    if(is_null($language)){
      $language = CurrentLanguage::$language;
    }

    $arr = $this->data->filter(function($entity) use ($language){
      return $entity->getLanguage() == $language;
    });
    $entity = $arr->first();
    if(!$entity){
      $entity = new PageData();
      $entity->setLanguage($language);
      $this->addData($entity);
    }
    return $entity;
  }
  /**
   * @ORM\PrePersist
   */
  public function setPrePersist()
  {
    $this->language = CurrentLanguage::$language;
  }

  public function addComment(Comment $comment) : void{
    $comment->setPage($this);
    $this->comments[] = $comment;
  }

  public function removeComment(Comment $comment) : void{
    $this->comments->remove($comment);
  }

  /**
   * @return ArrayCollection
   */
  public function getComments() : ArrayCollection
  {
    return $this->comments;
  }

  public function getCommentPublished(){
    return $this->comments->filter(function($commnet){
      return $commnet->getMarking() == 'publish';
    });
  }

  public function getCommentUnpublished(){
    return $this->comments->filter(function($commnet){
      return $commnet->getMarking() == 'unpublish';
    });
  }


}

src/Entity/PageData.php
<?php


namespace App\Entity;

use App\Components\Language\CurrentLanguage;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Uv\Core\Entity\EntityIdTrait;
use Uv\Core\Entity\EntityUpdateTrait;
use Uv\File\Entity\File;


/**
 * Class Page
 * @package PageBundle\Entity
 * @ORM\Entity
 * @ORM\Table(name="page_data")
 * @ORM\HasLifecycleCallbacks()
 */
class PageData
{

  use EntityIdTrait;
  use EntityUpdateTrait;

  /**
   * @ORM\ManyToOne(targetEntity="Page", inversedBy="data")
   * @ORM\JoinColumn(name="page_id", referencedColumnName="id")
   */
  private $page;

  /**
   * @ORM\Column(type="string", length=191)
   */
  private $title;

  /**
   * @ORM\Column(type="string", length=191)
   */
  private $language;
  /**
   * @ORM\Column(type="datetime")
   */
  private $created;

  /**
   * @ORM\Column(type="string", length=191, nullable=true)
   */
  private $marking;

  /**
   * @ORM\OneToMany(targetEntity="PageBody", mappedBy="entity", cascade={"persist", "remove"})
   */
  private $body;

  /**
   * @ORM\ManyToOne(targetEntity="Term")
   * @ORM\JoinColumn(name="term_id", referencedColumnName="id")
   */

  private $category;
  /**
   * @ORM\OneToOne(targetEntity="Uv\File\Entity\File", cascade={"persist", "remove"})
   * @ORM\JoinColumn(name="image_fid", referencedColumnName="id")
   */
  private $image;

  public function __construct()
  {
    $this->body = new ArrayCollection();
  }


  /**
   * @return Page
   */
  public function getPage()
  {
    return $this->page;
  }

  /**
   * @param mixed $page
   */
  public function setPage($page): void
  {
    $this->page = $page;
  }

  /**
   * @return mixed
   */
  public function getTitle()
  {
    return $this->title;
  }

  /**
   * @param mixed $title
   */
  public function setTitle($title): void
  {
    $this->title = $title;
  }

  /**
   * @return mixed
   */
  public function getLanguage()
  {
    return $this->language;
  }

  /**
   * @param mixed $language
   */
  public function setLanguage($language): void
  {
    $this->language = $language;
  }

  /**
   * @return mixed
   */
  public function getCreated()
  {
    return $this->created;
  }

  /**
   * @param mixed $created
   */
  public function setCreated($created): void
  {
    $this->created = $created;
  }

  /**
   * @return mixed
   */
  public function getMarking()
  {
    return $this->marking;
  }

  /**
   * @param mixed $marking
   */
  public function setMarking($marking): void
  {
    $this->marking = $marking;
  }

  /**
   * @return mixed
   */
  public function getBody()
  {
    return $this->body;
  }


  /**
   * @param PageBody $body
   */
  public function addBody(PageBody $body): void
  {
    $body->setEntity($this);
    $this->body->add($body);
  }

  /**
   * @return PageBody
   */
  public function getFieldBody(){
    return $this->body->first();
  }

  /**
   * @return Term
   */
  public function getCategory()
  {
    return $this->category;
  }
  public function setCategory(Term $term){
    $this->category = $term;
    return $this;
  }


  /**
   * @ORM\PrePersist
   */
  public function setPrePersist()
  {
    if(is_null($this->language)){
      $this->language = $this->getPage()->getLanguage();
    }
    $this->created = new \DateTime();
    $this->marking = 'draft';
  }

  /**
   * @return mixed
   */
  public function getImage()
  {
    return $this->image;
  }

  /**
   * @param mixed $image
   */
  public function setImage($image): void
  {
    $this->image = $image;
  }

  public function removeBody(PageBody $body): self
  {
      if ($this->body->contains($body)) {
          $this->body->removeElement($body);
          // set the owning side to null (unless already changed)
          if ($body->getEntity() === $this) {
              $body->setEntity(null);
          }
      }

      return $this;
  }



}

templates/Page/add.html.twig
{% extends 'page_default.html.twig' %}
{% block main %}
  <div class="block block--page-add">
    <div class="block-content">
      {{ form(form) }}
    </div>
  </div>
{% endblock %}

templates/Page/delete.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-delete">
    <div class="block-content">
      {{ form(form) }}
    </div>
  </div>

{% endblock %}

templates/Page/edit.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-edit">
    <div class="block-content">
      {{ form_start(form) }}
      {{ form_row(form.title) }}
      {{ form_row(form.language) }}
      <div class="lt lt-form-image-row">
          <div class="lt-r lt-r--left">
              {% if page_data.image is not null %}
                  <div class="field field-image">{{ page_data.image|image_style('100_100_crop') }}</div>
              {% endif %}
          </div>
          {{ form_row(form.image) }}
      </div>
      {#{{ form_widget(form) }}#}
      {{ form_end(form) }}

    </div>
  </div>

{% endblock %}

templates/Page/list-ajax.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-list">
    <div class="block-content">
      <div class="list list--page-list" id="page_list_navigation">
        {% for page in pages %}
          <div class="list-item">
            {{  include('Page/ViewMode/teaser.html.twig', { 'item' : page } )  }}
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="block-navigation">
      <div class="pager-btn">
        <button id="page_load_more" data-page="1">Load more</button>
      </div>
    </div>
  </div>


{% endblock %}

templates/Page/list.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-list">
    <div class="block-content">
      <div class="list list--page-list">
        {% for page in pages %}
          <div class="list-item">
            {{  include('Page/ViewMode/teaser.html.twig', { 'item' : page } )  }}
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="block-navigation">
      <ul class="pager">
        {% if navigator.pager > 1 %}
          <li class="pager-item"><a href="{{ path('page_list', { 'page' : navigator.pager - 1 }) }}">back</a></li>
        {% endif %}
        <li class="pager-item">{{ navigator.pager }}</li>
        {% if navigator.pager*navigator.limit < navigator.total %}
          <li class="pager-item"><a href="{{ path('page_list', { 'page' : navigator.pager + 1 }) }}">next</a></li>
        {% endif %}
      </ul>
    </div>
  </div>


{% endblock %}

templates/Page/page_comments.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-view">
    <div class="block-content">
      <h2 class="field field-title">{{ page.title }}</h2>
      <div class="field field-comments">
        <div class="comment-preview">
          <h2 class="comment-title">Comments</h2>
          <div class="list">
            {% for item in comments %}
              <div class="list-item">
                {{ include('Comments/ViewMode/teaser.html.twig', {'item' : item }) }}
                <ul>
                  <li><a href="{{ path('comment_edit', { 'id' : item.id }) }}">Edit</a></li>
                  <li><a href="{{ path('comment_delete', { 'id' : item.id }) }}">Delete</a></li>
                </ul>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

    </div>
    <div class="block-navigation">
      <ul class="pager">
        {% if navigator.pager > 1 %}
          <li class="pager-item"><a href="{{ path('page_comments', { 'id' : page.id, 'pager' : navigator.pager - 1 }) }}">back</a></li>
        {% endif %}
        <li class="pager-item">{{ navigator.pager }}</li>
        {% if navigator.pager*navigator.limit < navigator.total %}
          <li class="pager-item"><a href="{{ path('page_comments', { 'id' : page.id, 'pager' : navigator.pager + 1 }) }}">next</a></li>
        {% endif %}
      </ul>
    </div>
  </div>

{% endblock %}

templates/Page/search.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-list">
    <div class="block-content">
      {{ form(form) }}
      <div class="list list--page-list">
        {% for page in pages %}
          <div class="list-item">
            {{  include('Page/ViewMode/teaser.html.twig', { 'item' : page } )  }}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>


{% endblock %}

templates/Page/translation.html.twig
{% extends 'page_default.html.twig' %}
{% block page_title %}Add Translation{% endblock %}
 {% block main %}
   <div class="block block--page-translation">
     <div class="block-content">

       <div class="list">
         {% for language in languages %}
           {% set entity = null %}
           {% set title = 'None' %}
           {% set route = path('page_add', {'trans_lg' : language.language, 'trand_id' : page.id }) %}
           {% set routeTitle = 'Add' %}
           {% if page.entities[language.language] is defined %}
             {% set entity = page.entities[language.language] %}
             {% set title = entity.title %}
             {% set route = path('page_edit', {'trans_lg' : language.language, 'id' : page.id }) %}
             {% set routeTitle =  'Edit' %}
           {% endif %}
           {{ dump(route) }}
           <div class="list-item">
             Language: {{ language.name }}
             Title: {{ title }}
             Actions: <a href="{{ route }}">{{ routeTitle }}</a>
           </div>

         {% endfor %}
       </div>
     </div>
   </div>

 {% endblock %}

templates/Page/view.html.twig
{% extends 'page_default.html.twig' %}
{% block page_title %}{{ page_data.title }}{% endblock %}
 {% block main %}
     <article class="block block--page-view page-view page-{{ page_data.page.id }}">
         <div class="block-content">
             <div class="fields fields-top">
                 {% if page_data.image is not null %}
                     <div class="field field-image">{{ page_data.image|image_style('200_200_crop') }}</div>
                 {% endif %}
                 <div class="field field-body">{{ page_data.fieldBody.body }}</div>
                 <div class="list-link">
                     {% if page_data.category %}
                         {% set category = "term." ~ page_data.category.machineName %}
                         <div class="list-link-item page-category"> {{ category|trans }}</div>
                     {% endif %}
                     <div class="list-link-item page-created">{{ page_data.created|date('d-m-Y') }}</div>
                 </div>
             </div>
             {% if is_granted('ROLE_ADMIN') and page_data.page.commentUnpublished|length > 0 %}
                 <div class="field field-comment-workflow">
                     <div class="comment-preview">
                         <h2 class="comment-title">Comments Unpublished</h2>
                         <div class="list">
                             {% for item in page_data.page.commentUnpublished %}
                                 <div class="list-item">
                                     {{ include('Comments/ViewMode/teaser.html.twig', {'item' : item }) }}
                                     <ul>
                                         <li><a href="{{ path('comment_view', { 'id' : item.id }) }}">Workflow</a></li>
                                     </ul>
                                 </div>
                             {% endfor %}
                         </div>
                     </div>
                 </div>
             {% endif %}

             <div class="field field-comments">
                 <div class="comment-preview">
                     {% if page_comments|length > 0 %}
                         <h2 class="comment-title">Comments</h2>
                     {% endif %}
                     {% if app.user is not null %}
                         {{ form(comment_form) }}
                     {% endif %}
                     <div class="list">
                         {% for item in page_comments %}
                             <div class="list-item">
                                 {{ include('Comments/ViewMode/teaser.html.twig', {'item' : item }) }}
                                 <ul>
                                     <li><a href="{{ path('comment_edit', { 'id' : item.id }) }}">Edit</a></li>
                                     <li><a href="{{ path('comment_delete', { 'id' : item.id }) }}">Delete</a></li>
                                 </ul>
                             </div>
                         {% endfor %}
                     </div>
                 </div>
             </div>

         </div>
     </article>

 {% endblock %}